version: '25.0.2'

services:
  mysqldb:
    image: mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=rootadmin
      - MYSQL_DATABASE=simonsays
    ports: 
      - 3307:3306

  app:
    build: .
    depends_on:
      - mysqldb
    links:
      - mysqldb
    ports:
      - 3000:3000
  